const STRINGS = {
  ua: {
    splashYear:'NO PREPAYMENT', splashTag:'МОДНИЙ ОДЯГ',
    splashChoose:'Оберіть свій розділ',
    spNopay:'Без передоплати', spNp:'Нова Пошта', spFit:'Примірка',
    sblMale:'Чоловічий', sblFemale:'Жіночий',
    sbcMale:'200+ образів', sbcFemale:'500+ образів',
    splashHint:'Можна змінити внизу сторінки',
    hdrSub:'МОДНИЙ ОДЯГ',
    greeting0:'Одягайся краще за всіх ☀️', greeting1:'Стиль без переплати 🔥',
    greeting2:'Look на вечір — тут 👗', greeting3:'Знаходимо. Ти береш. 🌙',
    homeTitle:'Твій ідеальний<br>образ тут 👗',
    popular:'🔥 Популярне зараз', newIn:'✨ Новинки',
    brands:'👗 Бренди', recent:'👀 Нещодавно переглянуті',
    allModels:'Весь асортимент', seeAll:'Всі',
    navHome:'Головна', navMatch:'Match', navCatalog:'Каталог', navContacts:'Контакти',
    gMale:'♂ Чоловічий', gFemale:'♀ Жіночий',
    sizesIn:'Розмір: ',
    updated:'🔄 Оновлено: сьогодні о',
    searchPh:'Пошук по назві або стилю…',
    models:'образів',
    noSizes:'Немає товарів з вибраними фільтрами',
    sizeLabel:'РОЗМІР',
    favsTitle:'Улюблені', cartTitle:'Кошик',
    favsEmpty:'Тут з\'являться образи,<br>які ти лайкнув у Match',
    cartEmpty:'Кошик порожній',
    matchLike:'ХОЧУ', matchNope:'НЕ ТЕ',
    matchDone:'Переглянуто все!',
    updated:'🔄 Оновлено о',
    csbLabel:'речей у кошику',
    cartItems:'шт.',
    cartDelivery:'Безкоштовно від 500₴',
    cartToPay:'До сплати:',
    cartCheckout:'Оформити замовлення →',
    cartRowItems:'Товари', cartRowDelivery:'Доставка',
    formName:'Ваше ім\'я', formPhone:'Номер телефону',
    formCity:'Місто', formDept:'Відділення НП',
    formPost:'Поштомат НП',
    deptPh:'Номер відділення', postPh:'Номер поштомату',
    submitting:'Відправляємо…', submitOrder:'Замовити →',
    mySizeLabel:'Мій розмір', mySizeTap:'Торкнись',
    scarcity1:'⚡️ Останній розмір!', scarcityLow:'🔥 Лише', scarcityLowSuffix:' розміри',
    sendReview:'Надіслати відгук',
    faqTitle:'❓ Часті запитання',
    faqItems:[
      {q:'Як замовити?', a:'Обери товар → натисни "Замовити" → вибери розмір → заповни форму. Все просто!'},
      {q:'Є примірка?', a:'Так! Ти отримуєш посилку на Нову Пошту, приміряєш і якщо не підходить — просто відмовляєшся. Безкоштовно.'},
      {q:'Скільки часу доставка?', a:'1–3 дні по всій Україні. Нова Пошта.'},
      {q:'Як дізнатися про новинки?', a:'Підпишись на наш Telegram-канал або дозволь push-сповіщення на сайті.'},
    ],
    catAll:'Все', catWear:'Одяг', catBilyzna:'Білизна',
  },
  en: {
    splashYear:'NO PREPAYMENT', splashTag:'FASHION WEAR',
    splashChoose:'Choose your style',
    spNopay:'No prepayment', spNp:'Nova Poshta', spFit:'Try-on',
    sblMale:'Men', sblFemale:'Women',
    sbcMale:'200+ styles', sbcFemale:'500+ styles',
    splashHint:'Can be changed below',
    hdrSub:'FASHION WEAR',
    greeting0:'Good morning! ☀️', greeting1:'Hey! 👋',
    greeting2:'Good evening! 🌙', greeting3:'Good night! 🌟',
    homeTitle:'Your perfect<br>look is here 👗',
    popular:'🔥 Popular now', newIn:'✨ New arrivals',
    brands:'👗 Brands', recent:'👀 Recently viewed',
    allModels:'All items', seeAll:'All',
    navHome:'Home', navMatch:'Match', navCatalog:'Catalog', navContacts:'Contacts',
    gMale:'♂ Men', gFemale:'♀ Women',
    sizesIn:'Size: ',
    updated:'🔄 Updated today at',
    searchPh:'Search by name or style…',
    models:'styles',
    noSizes:'No products with selected filters',
    sizeLabel:'SIZE',
    favsTitle:'Favourites', cartTitle:'Cart',
    favsEmpty:'Liked items<br>will appear here',
    cartEmpty:'Cart is empty',
    matchLike:'WANT', matchNope:'NOPE',
    matchDone:'All seen!',
    csbLabel:'items in cart',
    cartItems:'pcs.',
    cartDelivery:'Free from 500₴',
    cartToPay:'Total:',
    cartCheckout:'Checkout →',
    cartRowItems:'Items', cartRowDelivery:'Delivery',
    formName:'Your name', formPhone:'Phone number',
    formCity:'City', formDept:'Nova Poshta branch',
    formPost:'Nova Poshta locker',
    deptPh:'Branch number', postPh:'Locker number',
    submitting:'Sending…', submitOrder:'Order →',
    mySizeLabel:'My size', mySizeTap:'Tap',
    scarcity1:'⚡️ Last size!', scarcityLow:'🔥 Only', scarcityLowSuffix:' sizes',
    sendReview:'Send review',
    faqTitle:'❓ FAQ',
    faqItems:[
      {q:'How to order?', a:'Choose item → tap Order → select size → fill form. Easy!'},
      {q:'Is try-on available?', a:'Yes! Receive at Nova Poshta, try it on. If it does not fit — refuse for free.'},
      {q:'Delivery time?', a:'1–3 days across Ukraine. Nova Poshta.'},
      {q:'How to know about new arrivals?', a:'Subscribe to our Telegram channel or allow push notifications.'},
    ],
    catAll:'All', catWear:'Clothing', catBilyzna:'Lingerie',
  },
};

let L = STRINGS.ua;
function applyLang() {
  L = STRINGS[S.lang] || STRINGS.ua;
  const hSub = document.getElementById('hdr-sub');
  if (hSub) hSub.textContent = L.hdrSub;
  const srch = document.getElementById('cat-search');
  if (srch) srch.placeholder = L.searchPh;
  renderFaq();
}
